import { CourseLevel, CourseStatus, CourseVm } from "./course/course.types";

export const mockCourses: CourseVm[] = [
  {
    id: "course-1",
    title: "Modern JavaScript From The Beginning 2.0 (2024)",
    status: CourseStatus.Published,
    summary: "A practical guide to learning TypeScript effectively.",
    description: "Covers everything from basic types to advanced generics and utility types.",
    imageUrl: "https://cdn.pixabay.com/photo/2025/04/17/12/03/girl-9540346_1280.jpg",
    promoVideoUrl: null,
    price: 100,
    discountPercentage: 20,
    discountedPrice: 80,
    rating: 4.6,
    ratingCount: 380,
    language: "English",
    level: CourseLevel.Beginner,
    studentEnrollmentCount: 1200,
    lectureCount: 20,
    sectionCount: 5,
    durationInSeconds: 7200,
    categoryName: "Programming",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-02-01T09:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-2",
    title: "React for Intermediate Developers",
    status: CourseStatus.Published,
    summary: "Understand React core concepts and build real-world apps.",
    description: "Includes hooks, context API, routing, and performance optimization.",
    imageUrl: "https://cdn.pixabay.com/photo/2025/03/30/13/01/fairy-tale-9502808_1280.jpg",
    promoVideoUrl: null,
    price: 120,
    discountPercentage: 25,
    discountedPrice: 90,
    rating: 4.5,
    ratingCount: 250,
    language: "English",
    level: CourseLevel.Intermediate,
    studentEnrollmentCount: 950,
    lectureCount: 30,
    sectionCount: 6,
    durationInSeconds: 10800,
    categoryName: "Front-end",
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-01-20T09:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-3",
    title: "Build RESTful APIs with ASP.NET Core",
    status: CourseStatus.Draft,
    summary: "Learn to develop secure and scalable web APIs using ASP.NET Core.",
    description: "Work with controllers, EF Core, JWT auth, versioning, and more.",
    imageUrl: "https://cdn.pixabay.com/photo/2025/02/02/17/46/man-9377284_1280.jpg",
    promoVideoUrl: null,
    price: 140,
    discountPercentage: 10,
    discountedPrice: 126,
    rating: 4.3,
    ratingCount: 170,
    language: "English",
    level: CourseLevel.Advanced,
    studentEnrollmentCount: 400,
    lectureCount: 25,
    sectionCount: 4,
    durationInSeconds: 9600,
    categoryName: "Back-end",
    createdAt: "2024-02-01T08:00:00Z",
    updatedAt: "2024-03-01T09:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-4",
    title: "Clean Architecture in .NET Projects",
    status: CourseStatus.Published,
    summary: "Build scalable and maintainable applications with Clean Architecture.",
    description: "Apply the principles of Clean Architecture to real-world .NET projects.",
    imageUrl: "https://cdn.pixabay.com/photo/2025/04/05/06/58/flower-9514615_1280.png",
    promoVideoUrl: null,
    price: 160,
    discountPercentage: 15,
    discountedPrice: 136,
    rating: 4.7,
    ratingCount: 210,
    language: "English",
    level: CourseLevel.Advanced,
    studentEnrollmentCount: 350,
    lectureCount: 18,
    sectionCount: 3,
    durationInSeconds: 8400,
    categoryName: "Back-end",
    createdAt: "2024-03-10T10:00:00Z",
    updatedAt: "2024-04-01T08:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-5",
    title: "Zustand: Modern State Management in React",
    status: CourseStatus.Published,
    summary: "Manage global state in React with a lightweight, intuitive approach.",
    description: "Learn Zustand by building projects and comparing it with Redux and Context.",
    imageUrl: "https://cdn.pixabay.com/photo/2025/04/02/09/50/cat-9508590_1280.jpg",
    promoVideoUrl: "https://youtube.com/watch?v=zustand-demo",
    price: 80,
    discountPercentage: 0,
    discountedPrice: 80,
    rating: 4.2,
    ratingCount: 95,
    language: "English",
    level: CourseLevel.Intermediate,
    studentEnrollmentCount: 700,
    lectureCount: 12,
    sectionCount: 2,
    durationInSeconds: 3600,
    categoryName: "Front-end",
    createdAt: "2024-04-01T07:00:00Z",
    updatedAt: "2024-04-10T10:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-6",
    title: "Data Structures & Algorithms Essentials",
    status: CourseStatus.Published,
    summary: "Strengthen your core programming skills with DSA.",
    description: "Covers arrays, linked lists, stacks, queues, sorting, and searching.",
    imageUrl: "https://cdn.pixabay.com/photo/2025/04/02/09/50/cat-9508590_1280.jpg",
    promoVideoUrl: null,
    price: 110,
    discountPercentage: 30,
    discountedPrice: 77,
    rating: 4.8,
    ratingCount: 620,
    language: "English",
    level: CourseLevel.Beginner,
    studentEnrollmentCount: 2100,
    lectureCount: 28,
    sectionCount: 6,
    durationInSeconds: 14400,
    categoryName: "Algorithms",
    createdAt: "2023-12-20T08:00:00Z",
    updatedAt: "2024-01-05T08:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-7",
    title: "DevOps Basics: Docker and CI/CD Pipelines",
    status: CourseStatus.Published,
    summary: "Automate your deployment with Docker and CI/CD workflows.",
    description: "Get started with containers and set up CI/CD with GitHub Actions.",
    imageUrl: "https://cdn.pixabay.com/photo/2025/02/12/11/54/spruce-9401398_1280.jpg",
    promoVideoUrl: null,
    price: 150,
    discountPercentage: 40,
    discountedPrice: 90,
    rating: 4.4,
    ratingCount: 160,
    language: "English",
    level: CourseLevel.Intermediate,
    studentEnrollmentCount: 680,
    lectureCount: 16,
    sectionCount: 4,
    durationInSeconds: 7200,
    categoryName: "DevOps",
    createdAt: "2024-03-05T08:00:00Z",
    updatedAt: "2024-03-15T08:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-8",
    title: "Advanced Git and Branching Strategies",
    status: CourseStatus.Draft,
    summary: "Take your Git skills to the next level.",
    description: "Learn about rebase, cherry-pick, git-flow, and resolving conflicts.",
    imageUrl: "https://cdn.pixabay.com/photo/2023/09/04/23/58/woman-8233937_1280.jpg",
    promoVideoUrl: null,
    price: 70,
    discountPercentage: 0,
    discountedPrice: 70,
    rating: 4.1,
    ratingCount: 45,
    language: "English",
    level: CourseLevel.Intermediate,
    studentEnrollmentCount: 420,
    lectureCount: 10,
    sectionCount: 2,
    durationInSeconds: 3000,
    categoryName: "Version Control",
    createdAt: "2024-04-01T08:00:00Z",
    updatedAt: "2024-04-01T09:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-9",
    title: "Software Modeling with UML",
    status: CourseStatus.Published,
    summary: "Visualize and document your software design with UML diagrams.",
    description: "Covers Use Case, Class, Sequence, and Activity diagrams in depth.",
    imageUrl: "https://cdn.pixabay.com/photo/2022/05/03/07/45/nature-7171136_1280.jpg",
    promoVideoUrl: null,
    price: 90,
    discountPercentage: 10,
    discountedPrice: 81,
    rating: 4.3,
    ratingCount: 88,
    language: "English",
    level: CourseLevel.Beginner,
    studentEnrollmentCount: 530,
    lectureCount: 15,
    sectionCount: 3,
    durationInSeconds: 4200,
    categoryName: "Software Engineering",
    createdAt: "2023-11-01T08:00:00Z",
    updatedAt: "2023-11-15T08:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-10",
    title: "Next.js & Server-side Rendering Mastery",
    status: CourseStatus.Published,
    summary: "Build high-performance SSR apps with Next.js.",
    description: "Understand SSG, SSR, routing, middleware, and API routes in Next.js.",
    imageUrl: "https://cdn.pixabay.com/photo/2024/12/24/10/04/kitchen-9288111_1280.jpg",
    promoVideoUrl: "https://youtube.com/watch?v=nextjs-demo",
    price: 180,
    discountPercentage: 15,
    discountedPrice: 153,
    rating: 4.6,
    ratingCount: 295,
    language: "English",
    level: CourseLevel.Advanced,
    studentEnrollmentCount: 890,
    lectureCount: 22,
    sectionCount: 5,
    durationInSeconds: 9600,
    categoryName: "Full-stack",
    createdAt: "2024-01-20T08:00:00Z",
    updatedAt: "2024-02-01T08:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
];
