import { CourseLevel, CourseStatus, CourseVm } from "./course/course.types";

export const mockCourses: CourseVm[] = [
  {
    id: "course-1",
    title: "Modern JavaScript From The Beginning 2.0 (2024)",
    status: CourseStatus.Published,
    summary: "A practical guide to learning TypeScript effectively.",
    description: "Covers everything from basic types to advanced generics and utility types.",
    imageUrl: "https://cdn.pixabay.com/photo/2025/04/17/12/03/girl-9540346_1280.jpg",
    promoVideoUrl: null,
    price: 100,
    discountPercentage: 20,
    discountedPrice: 80,
    averageRating: 4.6,
    reviewCount: 380,
    language: "English",
    level: CourseLevel.Beginner,
    enrollmentCount: 1200,
    lectureCount: 20,
    sectionCount: 5,
    durationInSeconds: 7200,
    categoryName: "Programming",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-02-01T09:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-2",
    title: "React for Intermediate Developers",
    status: CourseStatus.Published,
    summary: "Understand React core concepts and build real-world apps.",
    description: "Includes hooks, context API, routing, and performance optimization.",
    imageUrl: "https://cdn.pixabay.com/photo/2025/03/30/13/01/fairy-tale-9502808_1280.jpg",
    promoVideoUrl: null,
    price: 120,
    discountPercentage: 25,
    discountedPrice: 90,
    averageRating: 4.5,
    reviewCount: 250,
    language: "English",
    level: CourseLevel.Intermediate,
    enrollmentCount: 950,
    lectureCount: 30,
    sectionCount: 6,
    durationInSeconds: 10800,
    categoryName: "Front-end",
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-01-20T09:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-3",
    title: "Build RESTful APIs with ASP.NET Core",
    status: CourseStatus.Draft,
    summary: "Learn to develop secure and scalable web APIs using ASP.NET Core.",
    description: "Work with controllers, EF Core, JWT auth, versioning, and more.",
    imageUrl: "https://cdn.pixabay.com/photo/2025/02/02/17/46/man-9377284_1280.jpg",
    promoVideoUrl: null,
    price: 140,
    discountPercentage: 10,
    discountedPrice: 126,
    averageRating: 4.3,
    reviewCount: 170,
    language: "English",
    level: CourseLevel.Advanced,
    enrollmentCount: 400,
    lectureCount: 25,
    sectionCount: 4,
    durationInSeconds: 9600,
    categoryName: "Back-end",
    createdAt: "2024-02-01T08:00:00Z",
    updatedAt: "2024-03-01T09:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-4",
    title: "Clean Architecture in .NET Projects",
    status: CourseStatus.Published,
    summary: "Build scalable and maintainable applications with Clean Architecture.",
    description: "Apply the principles of Clean Architecture to real-world .NET projects.",
    imageUrl: "https://cdn.pixabay.com/photo/2025/04/05/06/58/flower-9514615_1280.png",
    promoVideoUrl: null,
    price: 160,
    discountPercentage: 15,
    discountedPrice: 136,
    averageRating: 4.7,
    reviewCount: 210,
    language: "English",
    level: CourseLevel.Advanced,
    enrollmentCount: 350,
    lectureCount: 18,
    sectionCount: 3,
    durationInSeconds: 8400,
    categoryName: "Back-end",
    createdAt: "2024-03-10T10:00:00Z",
    updatedAt: "2024-04-01T08:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-5",
    title: "Zustand: Modern State Management in React",
    status: CourseStatus.Published,
    summary: "Manage global state in React with a lightweight, intuitive approach.",
    description: "Learn Zustand by building projects and comparing it with Redux and Context.",
    imageUrl: "https://cdn.pixabay.com/photo/2025/04/02/09/50/cat-9508590_1280.jpg",
    promoVideoUrl: "https://youtube.com/watch?v=zustand-demo",
    price: 80,
    discountPercentage: 0,
    discountedPrice: 80,
    averageRating: 4.2,
    reviewCount: 95,
    language: "English",
    level: CourseLevel.Intermediate,
    enrollmentCount: 700,
    lectureCount: 12,
    sectionCount: 2,
    durationInSeconds: 3600,
    categoryName: "Front-end",
    createdAt: "2024-04-01T07:00:00Z",
    updatedAt: "2024-04-10T10:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-6",
    title: "Data Structures & Algorithms Essentials",
    status: CourseStatus.Published,
    summary: "Strengthen your core programming skills with DSA.",
    description: "Covers arrays, linked lists, stacks, queues, sorting, and searching.",
    imageUrl: "https://cdn.pixabay.com/photo/2025/04/02/09/50/cat-9508590_1280.jpg",
    promoVideoUrl: null,
    price: 110,
    discountPercentage: 30,
    discountedPrice: 77,
    averageRating: 4.8,
    reviewCount: 620,
    language: "English",
    level: CourseLevel.Beginner,
    enrollmentCount: 2100,
    lectureCount: 28,
    sectionCount: 6,
    durationInSeconds: 14400,
    categoryName: "Algorithms",
    createdAt: "2023-12-20T08:00:00Z",
    updatedAt: "2024-01-05T08:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-7",
    title: "DevOps Basics: Docker and CI/CD Pipelines",
    status: CourseStatus.Published,
    summary: "Automate your deployment with Docker and CI/CD workflows.",
    description: "Get started with containers and set up CI/CD with GitHub Actions.",
    imageUrl: "https://cdn.pixabay.com/photo/2025/02/12/11/54/spruce-9401398_1280.jpg",
    promoVideoUrl: null,
    price: 150,
    discountPercentage: 40,
    discountedPrice: 90,
    averageRating: 4.4,
    reviewCount: 160,
    language: "English",
    level: CourseLevel.Intermediate,
    enrollmentCount: 680,
    lectureCount: 16,
    sectionCount: 4,
    durationInSeconds: 7200,
    categoryName: "DevOps",
    createdAt: "2024-03-05T08:00:00Z",
    updatedAt: "2024-03-15T08:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-8",
    title: "Advanced Git and Branching Strategies",
    status: CourseStatus.Draft,
    summary: "Take your Git skills to the next level.",
    description: "Learn about rebase, cherry-pick, git-flow, and resolving conflicts.",
    imageUrl: "https://cdn.pixabay.com/photo/2023/09/04/23/58/woman-8233937_1280.jpg",
    promoVideoUrl: null,
    price: 70,
    discountPercentage: 0,
    discountedPrice: 70,
    averageRating: 4.1,
    reviewCount: 45,
    language: "English",
    level: CourseLevel.Intermediate,
    enrollmentCount: 420,
    lectureCount: 10,
    sectionCount: 2,
    durationInSeconds: 3000,
    categoryName: "Version Control",
    createdAt: "2024-04-01T08:00:00Z",
    updatedAt: "2024-04-01T09:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-9",
    title: "Software Modeling with UML",
    status: CourseStatus.Published,
    summary: "Visualize and document your software design with UML diagrams.",
    description: "Covers Use Case, Class, Sequence, and Activity diagrams in depth.",
    imageUrl: "https://cdn.pixabay.com/photo/2022/05/03/07/45/nature-7171136_1280.jpg",
    promoVideoUrl: null,
    price: 90,
    discountPercentage: 10,
    discountedPrice: 81,
    averageRating: 4.3,
    reviewCount: 88,
    language: "English",
    level: CourseLevel.Beginner,
    enrollmentCount: 530,
    lectureCount: 15,
    sectionCount: 3,
    durationInSeconds: 4200,
    categoryName: "Software Engineering",
    createdAt: "2023-11-01T08:00:00Z",
    updatedAt: "2023-11-15T08:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
  {
    id: "course-10",
    title: "Next.js & Server-side Rendering Mastery",
    status: CourseStatus.Published,
    summary: "Build high-performance SSR apps with Next.js.",
    description: "Understand SSG, SSR, routing, middleware, and API routes in Next.js.",
    imageUrl: "https://cdn.pixabay.com/photo/2024/12/24/10/04/kitchen-9288111_1280.jpg",
    promoVideoUrl: "https://youtube.com/watch?v=nextjs-demo",
    price: 180,
    discountPercentage: 15,
    discountedPrice: 153,
    averageRating: 4.6,
    reviewCount: 295,
    language: "English",
    level: CourseLevel.Advanced,
    enrollmentCount: 890,
    lectureCount: 22,
    sectionCount: 5,
    durationInSeconds: 9600,
    categoryName: "Full-stack",
    createdAt: "2024-01-20T08:00:00Z",
    updatedAt: "2024-02-01T08:00:00Z",
    learningOutcomes: null,
    prerequisites: null,
  },
];

const initialSections = [
  {
    id: "sec-1",
    title: "Chapter 1: Building Responsive & Adaptive User Interfaces [EXPENSE TRACKER APP]",
    description: "Learn the basics of UX/UI through hands-on project.",
    courseId: "course-1",
    lectures: [
      {
        id: "lec-1",
        title: "Introduction to UX/UI Design",
        description: "Overview of user experience and interface design.",
        videoUrl: "https://example.com/video1.mp4",
        isPreview: true,
        durationInSeconds: 315,
        sectionId: "sec-1",
      },
      {
        id: "lec-2",
        title: "UX Writing & Content Strategy",
        description: "Writing content that aligns with user needs.",
        videoUrl: "https://example.com/video2.mp4",
        isPreview: false,
        durationInSeconds: 630,
        sectionId: "sec-1",
      },
      {
        id: "lec-3",
        title: "Design Thinking & User Research",
        description: "Learn user research and apply design thinking.",
        videoUrl: "https://example.com/video3.mp4",
        isPreview: true,
        durationInSeconds: 945,
        sectionId: "sec-1",
      },
      {
        id: "lec-4",
        title: "Usability Testing & Iteration",
        description: "Testing with users and improving your design.",
        videoUrl: "https://example.com/video4.mp4",
        isPreview: true,
        durationInSeconds: 1100,
        sectionId: "sec-1",
      },
      {
        id: "lec-5",
        title: "Submit a pull request once you are done",
        description: "Final steps and submission.",
        videoUrl: "https://example.com/video5.mp4",
        isPreview: false,
        durationInSeconds: 1500,
        sectionId: "sec-1",
      },
    ],
    lectureCount: 5,
    durationInSeconds: 4390,
  },
  {
    id: "sec-2",
    title: "Chapter 2: Advanced Techniques",
    description: "Enhance your skills with advanced tools.",
    courseId: "course-1",
    lectures: [
      {
        id: "lec-6",
        title: "Photo Editing Basics",
        description: "Introduction to editing tools.",
        videoUrl: "https://example.com/video6.mp4",
        isPreview: true,
        durationInSeconds: 315,
        sectionId: "sec-2",
      },
      {
        id: "lec-7",
        title: "Advanced Photoshop Techniques",
        description: "Master advanced editing tricks.",
        videoUrl: "https://example.com/video7.mp4",
        isPreview: false,
        durationInSeconds: 630,
        sectionId: "sec-2",
      },
      {
        id: "lec-8",
        title: "Creating Stunning Visuals",
        description: "Create visuals that captivate users.",
        videoUrl: "https://example.com/video8.mp4",
        isPreview: false,
        durationInSeconds: 945,
        sectionId: "sec-2",
      },
      {
        id: "lec-9",
        title: "Photo Retouching & Restoration",
        description: "Fix and restore old or flawed photos.",
        videoUrl: "https://example.com/video9.mp4",
        isPreview: true,
        durationInSeconds: 1200,
        sectionId: "sec-2",
      },
      {
        id: "lec-10",
        title: "Submit a pull request once you are done",
        description: "Wrap up the module.",
        videoUrl: "https://example.com/video10.mp4",
        isPreview: false,
        durationInSeconds: 1500,
        sectionId: "sec-2",
      },
    ],
    lectureCount: 5,
    durationInSeconds: 4590,
  },
  {
    id: "sec-3",
    title: "Chapter 3: Mockups & Prototypes",
    description: "Bring your ideas to life with prototypes.",
    courseId: "course-1",
    lectures: [
      {
        id: "lec-11",
        title: "Previewing Your Work",
        description: "Learn to preview your work effectively.",
        videoUrl: "https://example.com/video11.mp4",
        isPreview: true,
        durationInSeconds: 315,
        sectionId: "sec-3",
      },
      {
        id: "lec-12",
        title: "Sharing with Clients",
        description: "Best practices for sharing and presenting.",
        videoUrl: "https://example.com/video12.mp4",
        isPreview: false,
        durationInSeconds: 630,
        sectionId: "sec-3",
      },
      {
        id: "lec-13",
        title: "Creating Mockups",
        description: "Design static mockups using Figma.",
        videoUrl: "https://example.com/video13.mp4",
        isPreview: false,
        durationInSeconds: 945,
        sectionId: "sec-3",
      },
      {
        id: "lec-14",
        title: "Feedback & Revisions",
        description: "Iterate your designs with feedback.",
        videoUrl: "https://example.com/video14.mp4",
        isPreview: true,
        durationInSeconds: 1200,
        sectionId: "sec-3",
      },
      {
        id: "lec-15",
        title: "Submit a pull request once you are done",
        description: "Final submission for review.",
        videoUrl: "https://example.com/video15.mp4",
        isPreview: false,
        durationInSeconds: 1500,
        sectionId: "sec-3",
      },
    ],
    lectureCount: 5,
    durationInSeconds: 4590,
  },
];

const sections = [
  {
    title: "Chapter 1: Building Responsive & Adaptive User Interfaces [EXPENSE TRACKER APP]",
    totalLectures: 8,
    totalDuration: "1h 45m",
    lectures: [
      { title: "Introduction to UX/UI Design", duration: "5:15" },
      { title: "UX Writing & Content Strategy", duration: "10:30" },
      { title: "Design Thinking & User Research", duration: "15:45" },
      { title: "Usability Testing & Iteration", duration: "18:20:00" },
      { title: "Submit a pull request once you are done", duration: "25:00" },
    ],
  },
  {
    title: "Chapter 2: Advanced Techniques",
    totalLectures: 10,
    totalDuration: "2h 15m",
    lectures: [
      { title: "Photo Editing Basics", duration: "5:15" },
      { title: "Advanced Photoshop Techniques", duration: "10:30" },
      { title: "Creating Stunning Visuals", duration: "15:45" },
      { title: "Photo Retouching & Restoration", duration: "20:00" },
      { title: "Submit a pull request once you are done", duration: "25:00" },
    ],
  },
  {
    title: "Chapter 3: Mockups & Prototypes",
    totalLectures: 5,
    totalDuration: "1h 30m",
    lectures: [
      { title: "Previewing Your Work", duration: "5:15" },
      { title: "Sharing with Clients", duration: "10:30" },
      { title: "Creating Mockups", duration: "15:45" },
      { title: "Feedback & Revisions", duration: "20:00" },
      { title: "Submit a pull request once you are done", duration: "25:00" },
    ],
  },
];

const mockOrders = [
  {
    id: "132E97B7-9543-4E90-A32D-BAAE4A09D705",
    date: "10/04/2025",
    method: "Card payment",
    status: "Success",
    statusColor: "text-green",
    items: [
      {
        title: "GLUMEFORM 1000 XR DHG 3X10",
        price: 2200,
        quantity: 2,
        thumbnail:
          "https://cdn.nhathuoclongchau.com.vn/unsafe/50x50/https://cms-prod.s3-sgn09.fptcloud.com/00503114_tam_bong_tre_em_kamicare_hop_tron_160_que_1_dau_xoan_1_dau_thuong_1958_642c_large_f9db5145e5.jpg",
      },
      {
        title: "Another Product",
        price: 2900,
        quantity: 1,
      },
    ],
  },
  {
    id: "132E97B7-1111-4E90-A32D-BAAE4A09D705",
    date: "12/14/2024",
    method: "Card payment",
    status: "Success",
    statusColor: "text-green",
    items: [
      {
        title: "KamiCare Antibacterial Cotton Buds (160 pcs) for kids - dual end",
        price: 32000,
        discountedPrice: 25600,
        quantity: 1,
        thumbnail:
          "https://cdn.nhathuoclongchau.com.vn/unsafe/50x50/https://cms-prod.s3-sgn09.fptcloud.com/DSC_00198_f2f6e60ea0.jpg",
      },
      {
        title: "Another product",
        price: 8000,
        quantity: 1,
      },
    ],
  },
];
